version: 1
service: .
build:
  engine: railpack
cpln:
  org: cpln-git-deploy
  gvc: development
roles:
  - name: cpln-test-bun
    type: web
    workload: cpln-test-bun
    command: "bun run server.ts"
    port: 3000
    healthPath: /healthz
    public: true
