version: 1
service: .
cpln:
  org: cpln-git-deploy
  gvc: development
roles:
  - name: cpln-test-bun
    type: web
    workload: cpln-test-bun
    dockerfile: Dockerfile
    port: 3000
    healthPath: /healthz
    public: true
